### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by derrgoo** [4v3ngR/pluto_tv_scraper#1]
Can you give a bit more directions. Sounds cool but I never worked with this before. How do we get this to work? 👍

**Comment by 4v3ngR** [comment]
in order to get it to work, you need npm and node installed on your machine. These apps can easily be installed in Linux and macOS (I don't know how to install it in Windows).

Once npm and node is installed, do the following:
1. check out the code
2. cd to the pluto_tv_scraper directory
3. run `npm install` (this will install the dependencies)
4. to generate the playlist and xml, run the command `node ./index.js`

It does take a while due to the way the pluto TV api works for getting epg information (30 channels per call). So just wait. If everything goes well, you'll have 4 files created in the current directory (plutotv_us.m3u8, plutotv_us.xml, plutotv_uk.m3u8, plutotv_uk.xml).

I hope that helps.

**Comment by Toei79** [comment]
> in order to get it to work, you need npm and node installed on your machine. These apps can easily be installed in Linux and macOS (I don't know how to install it in Windows).
> 
> Once npm and node is installed, do the following:
> 
>     1. check out the code
> 
>     2. cd to the pluto_tv_scraper directory
> 
>     3. run `npm install` (this will install the dependencies)
> 
>     4. to generate the playlist and xml, run the command `node ./index.js`
> 
> 
> It does take a while due to the way the pluto TV api works for getting epg information (30 channels per call). So just wait. If everything goes well, you'll have 4 files created in the current directory (plutotv_us.m3u8, plutotv_us.xml, plutotv_uk.m3u8, plutotv_uk.xml).
> 
> I hope that helps.

question how i able to generate from other countries? for example i change uk ip for sweeden and works
but its not working if i add other line
i did this

const sw = '83.145.40.200';

and
await get('sw');

but i get a .m3u8 with uk channels

**Comment by 4v3ngR** [comment]
Thanks for the update. I've updated the mapping code (in index.js). Now other IP addresses and region codes can be added. I've already added the Sweeden entry for you

**Comment by derrgoo** [comment]
> in order to get it to work, you need npm and node installed on your machine. These apps can easily be installed in Linux and macOS (I don't know how to install it in Windows).
> 
> 
> 
> Once npm and node is installed, do the following:
> 
> 1. check out the code
> 
> 2. cd to the pluto_tv_scraper directory
> 
> 3. run `npm install` (this will install the dependencies)
> 
> 4. to generate the playlist and xml, run the command `node ./index.js`
> 
> 
> 
> It does take a while due to the way the pluto TV api works for getting epg information (30 channels per call). So just wait. If everything goes well, you'll have 4 files created in the current directory (plutotv_us.m3u8, plutotv_us.xml, plutotv_uk.m3u8, plutotv_uk.xml).
> 
> 
> 
> I hope that helps.

Thanks bro. Wish I was more tech savvy. Cool to see community chip in! Hopefully another way comes along that most of Matt's users can do with little technical ability.

**Comment by Toei79** [comment]
> Thanks for the update. I've updated the mapping code (in index.js). Now other IP addresses and region codes can be added. I've already added the Sweeden entry for you

still getting error if i add a new file on the other file

![image](https://github.com/4v3ngR/pluto_tv_scraper/assets/79808610/a99304ff-a33f-4a33-9ae5-3e58ab8e6d52)

**Comment by Toei79** [comment]
> > in order to get it to work, you need npm and node installed on your machine. These apps can easily be installed in Linux and macOS (I don't know how to install it in Windows).
> > Once npm and node is installed, do the following:
> > 
> > 1. check out the code
> > 2. cd to the pluto_tv_scraper directory
> > 3. run `npm install` (this will install the dependencies)
> > 4. to generate the playlist and xml, run the command `node ./index.js`
> > 
> > It does take a while due to the way the pluto TV api works for getting epg information (30 channels per call). So just wait. If everything goes well, you'll have 4 files created in the current directory (plutotv_us.m3u8, plutotv_us.xml, plutotv_uk.m3u8, plutotv_uk.xml).
> > I hope that helps.
> 
> Thanks bro. Wish I was more tech savvy. Cool to see community chip in! Hopefully another way comes along that most of Matt's users can do with little technical ability.

its more easier that you think , only you need a linux server even other options are there. and run this

i was failing for this for one ","
