### ISSUE TITLE
Suggestion: Ability to append #EXTM3U x-tvg-url="https://dummy.com/url/language.xml"

### ISSUE THREAD

**Issue by wazerstar** [4v3ngR/pluto_tv_scraper#10]
When generation the m3u8 file, it would be cool to have something like this for the first line in the file.

--xml-url=https://dummy.com/url/language.xml

So in this example this is the first and second line.

```
#EXTM3U x-tvg-url="https://dummy.com/url/language.xml"
#EXTINF:-1 tvg-id="XXXXXXXXXXXX" tvg-logo="https://images.pluto.tv/channels/XXXXXXXXXX/colorLogoPNG.png" tvg-chno="1" group-title="Nyt på Pluto TV", All exclusive
```

**Comment by 4v3ngR** [comment]
Quick question regarding this request... do you want the "language.xml" to be determined at runtime? (eg `x-tvg-url="https://dummy.com/url/plutotv_us.xml"`) or is it that the caller would provide the full url to the xml and the script will blindly add it to the `EXTM3U` header?

If it is the former, I think a `--base-url` property would be more approriate which would contain only `https://dummy.com/url/` and the script would append the full name of the xml file. This would allow each region's playlist to reference the corresponding xml.

Thoughts?

**Comment by wazerstar** [comment]
> Quick question regarding this request... do you want the "language.xml" to be determined at runtime? (eg `x-tvg-url="https://dummy.com/url/plutotv_us.xml"`) or is it that the caller would provide the full url to the xml and the script will blindly add it to the `EXTM3U` header?
> 
> If it is the former, I think a `--base-url` property would be more approriate which would contain only `https://dummy.com/url/` and the script would append the full name of the xml file. This would allow each region's playlist to reference the corresponding xml.
> 
> Thoughts?

I want us self to be able to call whatever the path is without you having to add anything into it.

So if I have https://dummy.com/url/plutotv_us.xml as url and I put that in, thats that it shows, and then any app that supports #EXTM3U x-tvg-url="url" will automatic pickup the EPG data.

**Comment by 4v3ngR** [comment]
how will your proposed solution work when multiple regions are configured?

**Comment by wazerstar** [comment]
> how will your proposed solution work when multiple regions are configured?

Does it generate multiple epg/xml files when using multiple regions?

**Comment by 4v3ngR** [comment]
`--x-tvg-url` as been added

**Comment by jeepcook** [comment]
> `--x-tvg-url` as been added

Hello, can the --x-tvg-url be different on each m3u8 or the same for all?

**Comment by 4v3ngR** [comment]
As I don't use this feature, I'm not going to change it from what it is. Happy to accept MRs to extend the functionality though.

**Comment by wazerstar** [comment]
> I might have an idea. If the provided url ends with a '/' the script will append the epg filename.

LOVELY, works really well, amazing job
