### ISSUE TITLE
Last commit generate a nodejs version error

### ISSUE THREAD

**Issue by jeepcook** [4v3ngR/pluto_tv_scraper#13]
On the last LTS Ubuntu version, the nodjs isn't compatible with the last commits done today.

Here is the error:

plutotv-scraper --group country --all
ERROR: nodejs is too old. Version 14 or greater is required.
ERROR: 12.22.9 installed

Note that the 23.10 isn't a stable Ubuntu release, the next LTS will be 22.04.

Thanks

**Comment by wazerstar** [comment]
I'm also getting some issues now with latest [commit](https://github.com/4v3ngR/pluto_tv_scraper/commit/392b23a7930c8d709efa347a309a3af0b3985f25)


```
C:\Users\mask\Desktop\pluto_tv_scraper-main\pluto_tv_scraper-main>node ./index.js --mapping dk
node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module 'commander'
Require stack:
- C:\Users\mask\Desktop\pluto_tv_scraper-main\pluto_tv_scraper-main\lib\config.js
- C:\Users\mask\Desktop\pluto_tv_scraper-main\pluto_tv_scraper-main\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at C:\Users\mask\Desktop\pluto_tv_scraper-main\pluto_tv_scraper-main\lib\config.js:3:18
    at Object.<anonymous> (C:\Users\mask\Desktop\pluto_tv_scraper-main\pluto_tv_scraper-main\lib\config.js:93:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\mask\\Desktop\\pluto_tv_scraper-main\\pluto_tv_scraper-main\\lib\\config.js',
    'C:\\Users\\mask\\Desktop\\pluto_tv_scraper-main\\pluto_tv_scraper-main\\index.js'
  ]
}

Node.js v20.11.0
```

**Comment by jeepcook** [comment]
> Try in the dir
> 
> npm install

npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'commander@11.1.0',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

added 1 package, and audited 13 packages in 1s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities


plutotv-scraper --group country --all
ERROR: nodejs is too old. Version 14 or greater is required.
ERROR: 12.22.9 installed

And I don't want to upgrade my Ubuntu distribution for a non stable one.

**Comment by jeepcook** [comment]
Finally after after having documented myself, I've found the information that the last LTS version for nodejs is v20.x. So I've decided to install the nodejs third part repository and force NODE_MAJOR=20.
So in conclusion now I have node in v20.11.0 version and the scraper is now repaired for my part.

**Comment by 4v3ngR** [comment]
I hadn't realised that commander required node 16 (I had already installed it prior to updating the package.json. I'll update minimum version checks to 16.

Note also, that node 12 stopped receiving security updates almost 2 years ago.
