### ISSUE TITLE
EPG Data is max 2 hours in front.

### ISSUE THREAD

**Issue by wazerstar** [4v3ngR/pluto_tv_scraper#15]
So I stumbled across this, when checking my old xml's from [i.mjh.nz](https://github.com/matthuisman/i.mjh.nz) and the data on the pluto website they are in line with 5-7 hours epg data where I'm now getting 1½ to 2hours max data with this script, the xml file is also around 3 times smaller than usual using mapping dk.

I made sure to check pluto website as of today and it's still a consistent of 5-7 hours of epg showing in their guides too, so what can the issue be here?

I noticed this when using my shield and could see right away that it said no information in the end of all channels in guide mode.

**Comment by 4v3ngR** [comment]
Thanks for that. 1.1.12 gets 24 hours of epg.
