### ISSUE TITLE
unique-client-id, can we have raw timestamp added to it after ip?

### ISSUE THREAD

**Issue by wazerstar** [4v3ngR/pluto_tv_scraper#16]
I assume that unique-client-id will generate the caller ip as unique-client-id, if you have something like caddy as reserve proxy, it will always assume its the server calling the the shot so the unique-client-id will always be server ip, to overcome this we could add a %timestamp% in raw milliseconds  or whatever the variable would be after ip to make it even more unique and avoid the reverseproxies getting back the original issue.

What do you think?

**Comment by 4v3ngR** [comment]
done

**Comment by wazerstar** [comment]
> done

Thanks, okay so There's a bug

--random-client-id cannot be run but --random-**clientid** can

also when I try to play http://localhost:port it does not regonize anything, what is the exact url when hosting via inbuilt server?

**Comment by 4v3ngR** [comment]
Thanks for that, the correct options are `--unique-clientid` and `--random-clientid`. I incorrectly added an extra hyphen in the help ouput, and subsequently copied it to other places. I've updated the help and readme.

**Comment by wazerstar** [comment]
> Thanks for that, the correct options are `--unique-clientid` and `--random-clientid`. I incorrectly added an extra hyphen in the help ouput, and subsequently copied it to other places. I've updated the help and readme.

Hey I tested again

while it accepts --random-clientid I checked and my client id is still "00000000-0000-0000-0000-000000000000"

I ran it like this

`node ./index.js --mapping dk --exclude-channels "How to use Pluto TV" --chno 92 --random-clientid --x-tvg-url "https://path.com"`

**Comment by 4v3ngR** [comment]
`--unique-clientid` and `--random-clientid` are only used in web server mode (when `--port` is provided) for it generates a new (unique or random) UUID as the m3u8 is requested. The m3u8 continues to contain the clientID configured.
