### ISSUE TITLE
Merge all regions into a single playlist and epg, Documentation

### ISSUE THREAD

**Issue by TazDevilLooney** [4v3ngR/pluto_tv_scraper#17]
Hi, I've tried various switches to the end of index.js -all and tried adding a second mapping into config.json. I'm able to get the outputs for the two regions separately but can't workout how to combine the two together. Could we have an updated document to help with this?  

Script works very well I'm just stuck on the combining.  Thanks

**Comment by 4v3ngR** [comment]
you could also use the `--all` command line option
