### ISSUE TITLE
France grabbing doesn't work anymore

### ISSUE THREAD

**Issue by jeepcook** [4v3ngR/pluto_tv_scraper#18]
Hello,

Since yesterday France grabbing doesn't work anymore.

Here is the error:
ERROR: got exception Cannot read properties of undefined (reading '0')

Everything is ok with other countries, log:
INFO: processing USA
INFO: processing Great Britain
INFO: processing Spain
INFO: processing Canada
INFO: processing Germany
INFO: processing France
ERROR: got exception Cannot read properties of undefined (reading '0')
INFO: processing Italy
INFO: processing Norway
INFO: processing Sweden
INFO: processing Denmark

My config for France:
"France": "88.190.245.208",

How to enable debug log instead of info ?

Thanks

**Comment by 4v3ngR** [comment]
This is an interesting one... it appears that there is a channel called "Pluto TV #1" that does not have a category. Playing the url just gives the "flying through space" pluto tv logo.

I've just pushed an update to filter out these channels.

**Comment by jeepcook** [comment]
No this channel has not to be filter out. It broadcasts programs, currently it's South Park. It's a "best of Pluto Tv" Channel.

![Capture d'écran 2024-01-27 073019](https://github.com/4v3ngR/pluto_tv_scraper/assets/17811804/d8f228a3-8c48-4960-bbc4-e1ed903487b6)
![Capture d'écran 2024-01-27 073105](https://github.com/4v3ngR/pluto_tv_scraper/assets/17811804/e9009bcc-6624-487b-a38b-6b30cd16d997)
