### ISSUE TITLE
Unable to add french (fr) channels

### ISSUE THREAD

**Issue by jeepcook** [4v3ngR/pluto_tv_scraper#2]
Hello, 

I added a french IP in the index.js, but the fr m3u and xml are not generated. 

Is there a log of the process to see where is the problem?

Thanks

**Comment by jeepcook** [comment]
Found the solution, we have to add 	await get('fr');  at the end of the index file.

**Comment by 4v3ngR** [comment]
Good idea, I should loop through the mapping keys. This way, adding a new mapping will automatically get it.

**Comment by 4v3ngR** [comment]
I've updated the code and moved the mapping into the config.json (no need to edit javascript files any more.

Thanks for the idea.
