### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by davidclaeysquinones** [4v3ngR/pluto_tv_scraper#20]
Hey I'm not sure if this is the right way to reach out so bear with me.

I've made a Docker image available at [my repo](https://git.claeyscloud.com/david/pluto_tv_scraper-docker) of the program.
Feel free to include it in this repo, or to include my repo as a reference.
I think it would benefit potential users quite a bit.

**Comment by 4v3ngR** [comment]
I've updated the readme to link to your repo. Thanks for that.
