### ISSUE TITLE
Add an option to create all.m3u8 and all.xml

### ISSUE THREAD

**Issue by jeepcook** [4v3ngR/pluto_tv_scraper#3]
Great great software. 

An idea would be to create separate m3u8 and xml for configured country as currently but also create all.m3u and all.xml containing all these countries.

Perhaps an option to configure in the indes.js or elsewhere.

Thanks ;-)

**Comment by jeepcook** [comment]
It's not an issue but a pull request, sorry

**Comment by 4v3ngR** [comment]
This would be an interesting one (especially for the XML file) - though as long as there isn't any collisions, it should be possible to simply concat the files (after removing the headers) and they should be valid.

**Comment by jeepcook** [comment]
It's to avoid collisions you've added -country after each tvg-id? Because in fact there is no collisions, every tvg-id are unique across all countries.

**Comment by 4v3ngR** [comment]
Previously I've observed pluto TV use the same channel ID in multiple regions - hence the suffix.

I'll also note that I've added some enhancements:

- added commandline options (including an --all option)
- added the ability to "install" the app (it can be executed as `plutotv-scraper`)
- full details (hopefully) in the README

**Comment by jeepcook** [comment]
Hello,

Thanks for this new and great update. 

For the all m3u8 and xml files I think I would be useful if the group-title was the country and not the original groupe-title. On Matt versions, for all files groupe-title were:
USA, Great Britain, Spain, Germany, France, Italy, Norway, Sweden, Denmark

What do you think about this ?

**Comment by jeepcook** [comment]
After tests, in fact in the all.m3u8 some channel groups are a mixed of some countries, they are in a same group of the one from another country. Just because the group name is the same, example: kids, sport, Music ....
I think that's why Matt changed the name groupes in the all.m3u and xml by the country name.
