### ISSUE TITLE
Improvment: Group all xml and m3u8 files by country

### ISSUE THREAD

**Issue by jeepcook** [4v3ngR/pluto_tv_scraper#4]
For the all m3u8 and xml files I think I would be useful if the group-title was the country and not the original groupe-title. On Matt versions, for all files groupe-title were:
USA, Great Britain, Spain, Germany, France, Italy, Norway, Sweden, Denmark

The files will be more readable as currently. We have 110 groups without the country name and some have the same names. It's confusing and incompatible with enigma2 fonctionnement. A ServiceRef for a provider has to be unique. But if the servicename and group are the same, the ServiceRef will be the same for these channels and only the first will be displayed and other will be hidden.

Thanks

**Comment by 4v3ngR** [comment]
I've added a "group" config option and a `--group` command line option which can have the values "genre" or "country". This will set the playlist group id to either the genre or the country.

The updated readme contains all the new options added.

**Comment by jeepcook** [comment]
Hello,

Cool update! We have now a very complete soft, with all necessary options.

Thanks for your work.
