### ISSUE TITLE
node on command line issue

### ISSUE THREAD

**Issue by Toei79** [4v3ngR/pluto_tv_scraper#5]
![image](https://github.com/4v3ngR/pluto_tv_scraper/assets/79808610/12b8d76e-0c19-4099-b172-4a374329bc0a)

i tried run this on command line but its not working. try to add it to crontab but . 

it runs on pluto tv scrapper but not out of it.

i did , install node -g

**Comment by 4v3ngR** [comment]
If you did `npm install -g .` you run the command with `plutotv-scraper` node will handle everything else. To test, run `plutotv-scraper --help`

The other way to run it is to cd to the pluto_tv_scraper directory and run `node ./index.js`

**Comment by 4v3ngR** [comment]
I've updated the readme to give clearer instructions on how to install the dependencies, and how to install the app, as well as the various ways it can be run.

**Comment by Toei79** [comment]
> I've updated the readme to give clearer instructions on how to install the dependencies, and how to install the app, as well as the various ways it can be run.

![image](https://github.com/4v3ngR/pluto_tv_scraper/assets/79808610/4ba2e416-5f19-4304-89f7-06a504c46da6)

i did something wrong? it runs but says local host only

**Comment by Toei79** [comment]
im ending doing a script .sh then do cd... and node on it, and works.
