### ISSUE TITLE
Suggestion: Ability to remove/ignore unessecary channels perhaps --ignore "channel name"

### ISSUE THREAD

**Issue by wazerstar** [4v3ngR/pluto_tv_scraper#8]
There's particular a channel called "How to use Pluto TV"

would be cool if it would be possible to do something like --ignore "How to use Pluto TV"

**Comment by 4v3ngR** [comment]
I've added an --ignore-groups option that can be given a regular expression (see the README for details). All groups that match the regular expression will be excluded from the playlist.

**Comment by wazerstar** [comment]
> I've added an --ignore-groups option that can be given a regular expression (see the README for details). All groups that match the regular expression will be excluded from the playlist.

Hey I just saw it before you posted, thanks but it does not really well for me?

If I read it right this will remove all groups that is called "Nyt på Pluto TV", which you don't want since there's many channels called that and its called for every new channel when its "new"

example from the xml
`#EXTINF:-1 tvg-id="xxx" tvg-logo="xx.png" tvg-chno="10" group-title="Nyt på Pluto TV", How to use Pluto TV`


group-title="`Nyt på Pluto TV`"
channel name = `How to use Pluto TV`

**Comment by 4v3ngR** [comment]
I've added another option `--exclude-channels <regex>`. It works the same as --exclude-groups but it checks the channel name and not the group name.

**Comment by wazerstar** [comment]
> I've added another option `--exclude-channels <regex>`. It works the same as --exclude-groups but it checks the channel name and not the group name.

Thank you a lot, I really appreciate this!
