### ISSUE TITLE
Suggestion: Ability to append another number as initial starting number for tvg-chno= 

### ISSUE THREAD

**Issue by wazerstar** [4v3ngR/pluto_tv_scraper#9]
When launching the script it will start with first channel having number 1.

When you have different m3u8 and others and combining them, it can be frustrated to have different files where they all start with 1 - and up.

Suggestion is to allow us to have something like --tvg-chno-start 55

Then the first initiate channel would be 55 and the next 56, and so on.

What do you think?

**Comment by 4v3ngR** [comment]
I've added a `--chno <num>` option. This is the first channel number and the channel numbers increment across all regions.
